### ISSUE TITLE
[consult] validator in service

### ISSUE THREAD

**Issue by Alice52** [arpitaggarwal/jsr-303#1]
Hi, @arpitaggarwal 

   I want to ask a question about jsr303, if validator was used in service, it will not work?

  
```java
// I annotate @Validated  to impl class, but it still not work
// and it only work in methods called by controller, Can you give me some advice?
private static String convertPassword(String password, @Validated @NotNull String salt)
      throws UnsupportedEncodingException {
    MD5 md5 = new MD5(salt.getBytes(CharsetUtil.UTF_8));
    return md5.digestHex(password);
}
```

I will appreciate, if I can get some replay,
Please forgive my nuisance， thanks.

**Comment by arpitaggarwal** [comment]
In the eyes of a Spring MVC stack, there is no such thing as a service layer. The reason it works for @Controller class handler methods is that Spring uses a special HandlerMethodArgumentResolver called ModelAttributeMethodProcessor which performs validation before resolving the argument to use in your handler method.

The service layer, as we call it, is just a plain bean with no additional behavior added to it from the MVC (DispatcherServlet) stack. As such you cannot expect any validation from Spring. You need to roll your own, probably with AOP.

Reference -https://stackoverflow.com/questions/19425221/spring-validated-in-service-layer#:~:text=In%20the%20eyes%20of%20a,use%20in%20your%20handler%20method.
